# -*- coding: utf-8 -*-
"""

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/
"""

!pip install langchain-experimental
!pip install tabulate
!pip install pandas
!pip install openai

#파이썬 언어로 작성된 데이터를 분석 및 조작하기 위한 라이브러리
import pandas as pd
#csv 파일을 데이터프레임으로 가져오기
df = pd.read_csv('/content/booksv_02.csv') #booksv_02.csv 파일이 있는 경로 지정
df.head()

from langchain_experimental.agents.agent_toolkits import create_pandas_dataframe_agent
from langchain.chat_models import ChatOpenAI
from langchain.agents.agent_types import AgentType
import os
os.environ["OPENAI_API_KEY"] = "sk-" #openai
#에이전트 생성
agent = create_pandas_dataframe_agent(
      ChatOpenAI(temperature=0, model='gpt-3.5-turbo'), #gpt-3.5-turbo 사용
      df, #데이터가 담긴 곳
      verbose=False, #추론 과정을 출력하지 않음
      agent_type=AgentType.OPENAI_FUNCTIONS,
     allow_dangerous_code=True # Add this line to acknowledge the risk and enable the functionality
)

agent.run('어떤 제품의 ratings_count가 제일 높아?')

agent.run('가장 최근에 출간된 책은?')